# Generated by Django 2.2 on 2019-04-17 06:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gymapp', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Cart',
        ),
    ]
